Study-MVC/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Study_MVC.Models {
    public class Employee {
        [Key]
        public int EmployeeId { get; set; }
        [Required(ErrorMessage ="Enter First Name")]
        public string FirstName { get; set; }
        [StringLength(5, ErrorMessage = "Last Name length should not be greater than 5")]
        public string LastName { get; set; }
        public int? Salary { get; set; }
    }
}

Study-MVC/Models/UserDetails.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Study_MVC.Models {
    public class UserDetails {
        [StringLength(7, MinimumLength = 2, ErrorMessage = "UserName length should be between 2 and 7")]
        public string UserName { get; set; }
        public string Password { get; set; }
    }


}

Study-MVC/ViewModels/CreateEmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Study_MVC.ViewModels {
    public class CreateEmployeeViewModel {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Salary { get; set; }
    }
}

Study-MVC/ViewModels/EmployeeListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Study_MVC.ViewModels {
    public class EmployeeListViewModel {
        public List<EmployeeViewModel> Employees { get; set; }
        public string UserName { get; set; }
    }
}

Study-MVC/ViewModels/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Study_MVC.ViewModels {
    public class EmployeeViewModel {
        public string EmployeeName { get; set; }
        public string Salary { get; set; }
        public string SalaryColor { get; set; }
    }
}

Study-MVC/Controllers/AuthenticationController.cs
using Study_MVC.BusinessLayer;
using Study_MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Study_MVC.Controllers
{
    public class AuthenticationController : Controller
    {
        // GET: Authenttication
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DoLogin(UserDetails u)
        {
            if (ModelState.IsValid)
            {
                EmployeeBusinessLayer bal = new EmployeeBusinessLayer();
                if (bal.IsValidUser(u))
                {
                    FormsAuthentication.SetAuthCookie(u.UserName, false);
                    return RedirectToAction("Index", "Employee");
                }
                else
                {
                    ModelState.AddModelError("CredentialError", "Invalid Username or Password");
                    return View("Login");
                }
            }
            else
            {
                return View("Login");
            }
        }
    }
}

Study-MVC/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Study_MVC.Models;
using Study_MVC.ViewModels;
using Study_MVC.BusinessLayer;

namespace Study_MVC.Controllers
{
    public class Customer {
        public string CustromerName { get; set; }
        public string Address { get; set; }

        public override string ToString() {
            return this.CustromerName + "|" + this.Address;
        }
    }

    public class EmployeeController : Controller
    {
        [Authorize]
        public ActionResult Index() {
            EmployeeListViewModel employeeListViewModel =
             new EmployeeListViewModel();

            EmployeeBusinessLayer empBal =
                     new EmployeeBusinessLayer();
            List<Employee> employees = empBal.GetEmployees();

            List<EmployeeViewModel> empViewModels =
                     new List<EmployeeViewModel>();

            foreach (Employee emp in employees) {
                EmployeeViewModel empViewModel =
                      new EmployeeViewModel();

                empViewModel.EmployeeName =
                      emp.FirstName + " " + emp.LastName;

                empViewModel.Salary = emp.Salary.GetValueOrDefault().ToString("C");
                if (emp.Salary > 15000) {
                    empViewModel.SalaryColor = "yellow";
                }
                else {
                    empViewModel.SalaryColor = "green";
                }
                empViewModels.Add(empViewModel);
            }
            employeeListViewModel.Employees = empViewModels;
            employeeListViewModel.UserName = User.Identity.Name;
            return View("Index", employeeListViewModel);

        }

        public ActionResult AddNew() {
            return View("CreateEmployee", new CreateEmployeeViewModel());
        } 

        public ActionResult SaveEmployee(Employee e, string BtnSubmit) {
            switch (BtnSubmit) {
                case "Save Employee":
                    if (ModelState.IsValid) {
                        var empBal = new EmployeeBusinessLayer();
                        empBal.SaveEmployee(e);
                        return RedirectToAction("Index");
                    }
                    else {
                        CreateEmployeeViewModel vm = new CreateEmployeeViewModel();
                        vm.FirstName = e.FirstName;
                        vm.LastName = e.LastName;
                        if (e.Salary.HasValue) {
                            vm.Salary = e.Salary.ToString();
                        }
                        else {
                            vm.Salary = ModelState["Salary"].Value.AttemptedValue;
                        }
                        return View("CreateEmployee", vm); // Day 4 Change - Passing e here
                    }
                case "Cancel":
                    return RedirectToAction("Index");
            }

            return new EmptyResult();
        }

        public Customer GetCustomer() {
            var c = new Customer();
            c.CustromerName = "Customer 1";
            c.Address = "Address1";
            return c;
        }       

        public string GetString() {
            return "Hello World is old now. It's time for wassup bro ;)";
        }
    }
}

Study-MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Study_MVC.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }

        public ActionResult About() {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact() {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Study-MVC/Views/Authentication/Login.cshtml
@model Study_MVC.Models.UserDetails

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>

    <script src="~/Scripts/jquery-1.8.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <div>
        @Html.ValidationMessage("CredentialError", new { style = "color:red;" })
        @using (Html.BeginForm("DoLogin", "Authentication", FormMethod.Post))
        {


            @Html.LabelFor(c => c.UserName)
            @Html.TextBoxFor(x => x.UserName)
            @Html.ValidationMessageFor(x => x.UserName)
            <br />

            @Html.LabelFor(c => c.Password)
            @Html.PasswordFor(x => x.Password)
            <br />

            <input type="submit" name="BtnSubmit" value="Login" />
        }
    </div>
</body>
</html>

Study-MVC/Views/Employee/CreateEmployee.cshtml
@using Study_MVC.ViewModels
@model CreateEmployeeViewModel
@{
    Layout = null;
}
<script src="~/Scripts/Validations.js"></script>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateEmployee</title>
</head>
<body>
    <div>
        <form action="/Employee/SaveEmployee" method="post">
            <table>
                <tr>
                    <td>
                        First Name:
                    </td>
                    <td>
                        <input type="text" id="TxtFName" name="FirstName" value="@Model.FirstName" />
                    </td>
                </tr>
                <tr>
                    <td colspan="2" align="right">
                        @Html.ValidationMessage("FirstName")
                    </td>
                </tr>
                <tr>
                    <td>
                        Last Name:
                    </td>
                    <td>
                        <input type="text" id="TxtLName" name="LastName" value="@Model.LastName" />
                    </td>
                </tr>
                <tr>
                    <td colspan="2" align="right">
                        @Html.ValidationMessage("LastName")
                    </td>
                </tr>

                <tr>
                    <td>
                        Salary:
                    </td>
                    <td>
                        <input type="text" id="TxtSalary" name="Salary" value="@Model.Salary" />
                    </td>
                </tr>
                <tr>
                    <td colspan="2" align="right">
                        @Html.ValidationMessage("Salary")
                    </td>
                </tr>

                <tr>
                    <td colspan="2">
                        <input type="submit" name="BtnSubmit" value="Save Employee"  onclick="return IsValid();" />
                        <input type="submit" name="BtnSubmit" value="Cancel" />
                        <input type="button" name="BtnReset" value="Reset" onclick="ResetForm();" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
</body>

</html>
<script>
    function ResetForm() {
        document.getElementById('TxtFName').value = "";
        document.getElementById('TxtLName').value = "";
        document.getElementById('TxtSalary').value = "";
    }
</script>

Study-MVC/Views/Employee/Index.cshtml
@using Study_MVC.ViewModels
@model EmployeeListViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetView</title>
</head>
<body>
    <div>
        <div style="text-align:right"> Hello, @Model.UserName 
        <a href="/Authentication/Logout">Logout</a></div>
        <hr />
        <a href="/Employee/AddNew">Add New</a>
        <table class="table">
            <tr>
                <th>Employee Name</th>
                <th>Salary</th>
                @foreach (EmployeeViewModel item in Model.Employees)
                {
                <tr>
                    <td>
                        @item.EmployeeName
                    </td>
                    <td style="background-color:@item.SalaryColor">@item.Salary</td>
                </tr>
                }
            <tr>
        </table>
    </div>

</body>
</html>

Study-MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Study-MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Study-MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Study-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>